### ISSUE TITLE
crashes when you rotate a square block

### ISSUE THREAD

**Issue by thisguycodes** [WRansohoff/Tetris-PebbleTime#1]
https://github.com/WRansohoff/Tetris-PebbleTime/blob/dd4ea99b197ea59d26ad6d06b34e730aef43792e/src/helpers.c#L86

``` C
  if (block_type == SQUARE) {
    // Haha, yeah no.
  }
```

fix ur shit man

**Comment by WRansohoff** [comment]
Guess I'd better fix that tonight. Same thing happens when you load a state where the current block is a square.
